name: black

on: pull_request

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.2.0
    - uses: actions/setup-python@v4
    - uses: pre-commit/action@v3.0.0
      with:
        extra_args: black
