name: HDMF Dev Branch Compatibility

on: [pull_request, workflow_dispatch]

jobs:
  check_compatibility:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel non-latest runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          all_but_latest: true
          access_token: ${{ github.token }}
          
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0  # tags are required for versioneer to determine the version
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install HDMF_Zarr Requirements
        run: |
          python -m pip install -r requirements-dev.txt -r requirements.txt
          pip install -e .
          
      - name: Clone HDMF Dev Branch
        run: |
          git clone https://github.com/hdmf-dev/hdmf.git --recurse-submodules
          cd hdmf
          python -m pip install -r requirements-dev.txt -r requirements.txt
          python -m pip install -e .
          cd ..

      - name: Run HDMF_Zarr Tests
        run:
          pytest -v tests
          
      
          
